# Top global companies by ATS platform.
# Greenhouse and Lever both expose public JSON APIs — no auth needed.
# Slugs that 404 are silently skipped by the scraper.

GREENHOUSE_COMPANIES = [
    # ── Big Tech & Infrastructure ──
    {"name": "Airbnb",          "slug": "airbnb"},
    {"name": "Stripe",          "slug": "stripe"},
    {"name": "Dropbox",         "slug": "dropbox"},
    {"name": "Box",             "slug": "box"},
    {"name": "Zendesk",         "slug": "zendesk"},
    {"name": "Twilio",          "slug": "twilio"},
    {"name": "Cloudflare",      "slug": "cloudflare"},
    {"name": "HashiCorp",       "slug": "hashicorp"},
    {"name": "Elastic",         "slug": "elastic"},
    {"name": "Confluent",       "slug": "confluent"},
    {"name": "Databricks",      "slug": "databricks"},
    {"name": "PagerDuty",       "slug": "pagerduty"},
    {"name": "Fastly",          "slug": "fastly"},
    {"name": "Datadog",         "slug": "datadog"},
    {"name": "Okta",            "slug": "okta"},
    {"name": "Splunk",          "slug": "splunk"},
    {"name": "New Relic",       "slug": "new-relic"},
    {"name": "Sumo Logic",      "slug": "sumologic"},
    {"name": "Dynatrace",       "slug": "dynatrace"},
    {"name": "CrowdStrike",     "slug": "crowdstrike"},
    {"name": "SentinelOne",     "slug": "sentinelone"},
    {"name": "Lacework",        "slug": "lacework"},
    {"name": "Wiz",             "slug": "wiz-inc"},
    {"name": "Orca Security",   "slug": "orca-security"},
    # ── Fintech ──
    {"name": "Brex",            "slug": "brex"},
    {"name": "Gusto",           "slug": "gusto"},
    {"name": "Ramp",            "slug": "ramp"},
    {"name": "Carta",           "slug": "carta"},
    {"name": "Plaid",           "slug": "plaid"},
    {"name": "Chime",           "slug": "chime"},
    {"name": "Coinbase",        "slug": "coinbase"},
    {"name": "Robinhood",       "slug": "robinhood"},
    {"name": "Marqeta",         "slug": "marqeta"},
    {"name": "Adyen",           "slug": "adyen"},
    {"name": "Klarna",          "slug": "klarna"},
    {"name": "Affirm",          "slug": "affirm"},
    {"name": "Toast",           "slug": "toastfinancial"},
    {"name": "Blend",           "slug": "blend"},
    {"name": "Navan",           "slug": "navan"},
    {"name": "Samsara",         "slug": "samsara"},
    # ── SaaS / Productivity ──
    {"name": "Asana",           "slug": "asana"},
    {"name": "Airtable",        "slug": "airtable"},
    {"name": "Amplitude",       "slug": "amplitude"},
    {"name": "Segment",         "slug": "segment"},
    {"name": "Intercom",        "slug": "intercom"},
    {"name": "HubSpot",         "slug": "hubspot"},
    {"name": "Typeform",        "slug": "typeform"},
    {"name": "SurveyMonkey",    "slug": "surveymonkey"},
    {"name": "Zenefits",        "slug": "zenefits"},
    {"name": "Lattice",         "slug": "lattice"},
    {"name": "Culture Amp",     "slug": "cultureamp"},
    {"name": "Workiva",         "slug": "workiva"},
    {"name": "Veeva",           "slug": "veeva"},
    {"name": "Procore",         "slug": "procore"},
    {"name": "Buildkite",       "slug": "buildkite"},
    {"name": "LaunchDarkly",    "slug": "launchdarkly"},
    {"name": "Split.io",        "slug": "split-io"},
    {"name": "FullStory",       "slug": "fullstory"},
    {"name": "LogRocket",       "slug": "logrocket"},
    {"name": "Heap",            "slug": "heap"},
    {"name": "Mixpanel",        "slug": "mixpanel"},
    # ── Dev Tools / Cloud ──
    {"name": "Netlify",         "slug": "netlify"},
    {"name": "CircleCI",        "slug": "circleci"},
    {"name": "Harness",         "slug": "harness-inc"},
    {"name": "Pulumi",          "slug": "pulumi"},
    {"name": "Temporal",        "slug": "temporal-technologies"},
    {"name": "Grafana Labs",    "slug": "grafana-labs"},
    {"name": "Honeycomb",       "slug": "honeycomb-io"},
    {"name": "Snyk",            "slug": "snyk"},
    {"name": "Sonar",           "slug": "sonarsource"},
    {"name": "JFrog",           "slug": "jfrog"},
    {"name": "Sentry",          "slug": "sentry"},
    {"name": "PostHog",         "slug": "posthog"},
    {"name": "Retool",          "slug": "retool"},
    # ── AI / ML ──
    {"name": "Scale AI",        "slug": "scaleai"},
    {"name": "Hugging Face",    "slug": "huggingface"},
    {"name": "Cohere",          "slug": "cohere"},
    {"name": "Stability AI",    "slug": "stability-ai"},
    {"name": "Weights & Biases","slug": "wandb"},
    {"name": "Labelbox",        "slug": "labelbox"},
    {"name": "Clarifai",        "slug": "clarifai"},
    {"name": "Determined AI",   "slug": "determined-ai"},
    {"name": "Runway",          "slug": "runwayml"},
    {"name": "Replit",          "slug": "replit"},
    # ── E-commerce / Marketplace ──
    {"name": "Shopify",         "slug": "shopify"},
    {"name": "BigCommerce",     "slug": "bigcommerce"},
    {"name": "Faire",           "slug": "faire"},
    {"name": "Whatnot",         "slug": "whatnot"},
    {"name": "Poshmark",        "slug": "poshmark"},
    {"name": "Depop",           "slug": "depop"},
    {"name": "StockX",          "slug": "stockx"},
    {"name": "GOAT",            "slug": "goat"},
    {"name": "Rover",           "slug": "rover-com"},
    # ── Healthcare / BioTech ──
    {"name": "Oscar Health",    "slug": "oscar"},
    {"name": "Tempus",          "slug": "tempus"},
    {"name": "Benchling",       "slug": "benchling"},
    {"name": "Flatiron Health", "slug": "flatiron"},
    {"name": "Veracyte",        "slug": "veracyte"},
    {"name": "Color Health",    "slug": "color"},
    {"name": "Hims & Hers",     "slug": "hims-hers"},
    {"name": "Noom",            "slug": "noom"},
    {"name": "Spring Health",   "slug": "spring-health"},
    # ── Media / Entertainment ──
    {"name": "Spotify",         "slug": "spotify"},
    {"name": "Vimeo",           "slug": "vimeo"},
    {"name": "Descript",        "slug": "descript"},
    {"name": "Substack",        "slug": "substack"},
    {"name": "Discord",         "slug": "discord"},
    {"name": "Twitch",          "slug": "twitch"},
    # ── Mobility / Logistics ──
    {"name": "Lime",            "slug": "lime"},
    {"name": "Via",             "slug": "via"},
    {"name": "Sonder",          "slug": "sonder"},
    {"name": "Vacasa",          "slug": "vacasa"},
    {"name": "Flexport",        "slug": "flexport"},
    {"name": "project44",       "slug": "project44"},
    # ── Real Estate / PropTech ──
    {"name": "Opendoor",        "slug": "opendoor"},
    {"name": "Compass",         "slug": "compass"},
    {"name": "Flyhomes",        "slug": "flyhomes"},
    # ── Enterprise / Other ──
    {"name": "Figma",           "slug": "figma"},
    {"name": "Miro",            "slug": "miro"},
    {"name": "Loom",            "slug": "loom"},
    {"name": "Coda",            "slug": "coda"},
    {"name": "Notion",          "slug": "notion"},
    {"name": "Pitch",           "slug": "pitch"},
    {"name": "Ahrefs",          "slug": "ahrefs"},
    {"name": "Semrush",         "slug": "semrush"},
    {"name": "Klaviyo",         "slug": "klaviyo"},
    {"name": "Sendbird",        "slug": "sendbird"},
    {"name": "Algolia",         "slug": "algolia"},
    {"name": "Contentful",      "slug": "contentful"},
    {"name": "Sanity",          "slug": "sanity-io"},
    {"name": "Stytch",          "slug": "stytch"},
    {"name": "WorkOS",          "slug": "workos"},
    {"name": "Ory",             "slug": "ory"},
    {"name": "Clerk",           "slug": "clerk"},
    {"name": "Auth0",           "slug": "auth0"},
    {"name": "1Password",       "slug": "1password"},
    {"name": "Bitwarden",       "slug": "bitwarden"},
    {"name": "Dashlane",        "slug": "dashlane"},
    {"name": "Aiven",           "slug": "aiven"},
    {"name": "PlanetScale",     "slug": "planetscale"},
    {"name": "Neon",            "slug": "neondatabase"},
    {"name": "SingleStore",     "slug": "singlestore"},
    {"name": "Pinecone",        "slug": "pinecone"},
    {"name": "Weaviate",        "slug": "weaviate"},
    {"name": "Qdrant",          "slug": "qdrant"},
    {"name": "Milvus / Zilliz", "slug": "zilliz"},
    {"name": "Supabase",        "slug": "supabase"},
    {"name": "Xata",            "slug": "xata"},
    {"name": "Turso",           "slug": "chiselstrike"},
    {"name": "Novu",            "slug": "novu"},
    {"name": "Courier",         "slug": "courier"},
    {"name": "Sendgrid",        "slug": "sendgrid"},
    {"name": "Mailchimp",       "slug": "mailchimp"},
    {"name": "Customer.io",     "slug": "customer-io"},
    {"name": "Iterable",        "slug": "iterable"},
    {"name": "Braze",           "slug": "braze"},
    {"name": "mParticle",       "slug": "mparticle"},
    {"name": "Treasure Data",   "slug": "treasure-data"},
    {"name": "LiveRamp",        "slug": "liveramp"},
    {"name": "Demandbase",      "slug": "demandbase"},
    {"name": "Gong",            "slug": "gong-io"},
    {"name": "Chorus",          "slug": "chorus-ai"},
    {"name": "Salesloft",       "slug": "salesloft"},
    {"name": "Outreach",        "slug": "outreach"},
    {"name": "Apollo",          "slug": "apollo-io"},
    {"name": "Clearbit",        "slug": "clearbit"},
    {"name": "ZoomInfo",        "slug": "zoominfo"},
    {"name": "Lusha",           "slug": "lusha"},
    {"name": "Clay",            "slug": "clay"},
    {"name": "Instantly",       "slug": "instantly"},
    {"name": "Lemlist",         "slug": "lemlist"},
    {"name": "Expensify",       "slug": "expensify"},
    {"name": "Divvy",           "slug": "divvy"},
    {"name": "Airbase",         "slug": "airbase"},
    {"name": "Spendesk",        "slug": "spendesk"},
    {"name": "Pleo",            "slug": "pleo"},
    {"name": "Payhawk",         "slug": "payhawk"},
    {"name": "Mesh Payments",   "slug": "mesh-payments"},
    {"name": "Deel",            "slug": "deel"},
    {"name": "Remote",          "slug": "remote-com"},
    {"name": "Rippling",        "slug": "rippling"},
    {"name": "Personio",        "slug": "personio"},
    {"name": "Workday",         "slug": "workday"},
    {"name": "BambooHR",        "slug": "bamboohr"},
    {"name": "Lever",           "slug": "lever"},
    {"name": "Greenhouse",      "slug": "greenhouse"},
    {"name": "Gem",             "slug": "gem"},
    {"name": "Ashby",           "slug": "ashby"},
    {"name": "Teamtailor",      "slug": "teamtailor"},
    {"name": "Workable",        "slug": "workable"},
    {"name": "Jobvite",         "slug": "jobvite"},
    {"name": "iCIMS",           "slug": "icims"},
]

LEVER_COMPANIES = [
    # ── Big Tech ──
    {"name": "Netflix",         "slug": "netflix"},
    {"name": "Lyft",            "slug": "lyft"},
    {"name": "Reddit",          "slug": "reddit"},
    {"name": "Snap",            "slug": "snap"},
    {"name": "DoorDash",        "slug": "doordash"},
    {"name": "Instacart",       "slug": "instacart"},
    {"name": "Rivian",          "slug": "rivian"},
    {"name": "Lucid Motors",    "slug": "lucidmotors"},
    {"name": "Waymo",           "slug": "waymo"},
    # ── Fintech ──
    {"name": "Mercury",         "slug": "mercury"},
    {"name": "Novo",            "slug": "novo"},
    {"name": "Pipe",            "slug": "pipe"},
    {"name": "Clearco",         "slug": "clearco"},
    {"name": "Jeeves",          "slug": "jeeves"},
    {"name": "Folio",           "slug": "folio"},
    {"name": "Synapse",         "slug": "synapsefi"},
    {"name": "Treasury Prime",  "slug": "treasuryprime"},
    {"name": "Unit",            "slug": "unit"},
    {"name": "Column",          "slug": "column"},
    {"name": "Sardine",         "slug": "sardine"},
    {"name": "Socure",          "slug": "socure"},
    {"name": "Alloy",           "slug": "alloy"},
    {"name": "Persona",         "slug": "withpersona"},
    # ── Dev Tools ──
    {"name": "Vercel",          "slug": "vercel"},
    {"name": "Railway",         "slug": "railway"},
    {"name": "Render",          "slug": "render"},
    {"name": "Fly.io",          "slug": "fly-io"},
    {"name": "Deno Land",       "slug": "deno-land"},
    {"name": "Socket.dev",      "slug": "socket-dev"},
    {"name": "Trunk",           "slug": "trunk-io"},
    {"name": "Codecov",         "slug": "codecov"},
    {"name": "Swimlane",        "slug": "swimlane"},
    {"name": "Cypress",         "slug": "cypress-io"},
    {"name": "Playwright (MS)", "slug": "microsoft"},
    {"name": "Doppler",         "slug": "doppler"},
    {"name": "Infisical",       "slug": "infisical"},
    # ── AI / ML ──
    {"name": "Anthropic",       "slug": "anthropic"},
    {"name": "OpenAI",          "slug": "openai"},
    {"name": "Mistral AI",      "slug": "mistral-ai"},
    {"name": "Together AI",     "slug": "together-ai"},
    {"name": "Perplexity",      "slug": "perplexity-ai"},
    {"name": "Character.AI",    "slug": "character-ai"},
    {"name": "Inflection AI",   "slug": "inflection-ai"},
    {"name": "Adept",           "slug": "adept"},
    {"name": "Magic",           "slug": "magic-ai"},
    {"name": "Imbue",           "slug": "imbue"},
    {"name": "Aisera",          "slug": "aisera"},
    {"name": "Writer",          "slug": "writer"},
    {"name": "Jasper",          "slug": "jasper-ai"},
    {"name": "Copy.ai",         "slug": "copy-ai"},
    {"name": "Synthesia",       "slug": "synthesia"},
    {"name": "ElevenLabs",      "slug": "elevenlabs"},
    {"name": "Pika",            "slug": "pika-labs"},
    {"name": "Midjourney",      "slug": "midjourney"},
    # ── Data / Analytics ──
    {"name": "dbt Labs",        "slug": "dbt-labs"},
    {"name": "Airbyte",         "slug": "airbyte"},
    {"name": "Fivetran",        "slug": "fivetran"},
    {"name": "Hightouch",       "slug": "hightouch"},
    {"name": "Census",          "slug": "getcensus"},
    {"name": "Hex",             "slug": "hex"},
    {"name": "Mode",            "slug": "mode-analytics"},
    {"name": "Sigma Computing", "slug": "sigmacomputing"},
    {"name": "ThoughtSpot",     "slug": "thoughtspot"},
    {"name": "Atlan",           "slug": "atlan"},
    {"name": "Secoda",          "slug": "secoda"},
    {"name": "Castor",          "slug": "castordoc"},
    # ── SaaS ──
    {"name": "Linear",          "slug": "linear"},
    {"name": "Canny",           "slug": "canny"},
    {"name": "Productboard",    "slug": "productboard"},
    {"name": "Pendo",           "slug": "pendo"},
    {"name": "Gainsight",       "slug": "gainsight"},
    {"name": "ChurnZero",       "slug": "churnzero"},
    {"name": "Totango",         "slug": "totango"},
    {"name": "Planhat",         "slug": "planhat"},
    {"name": "Vitally",         "slug": "vitally"},
    {"name": "Catalyst",        "slug": "catalyst"},
    {"name": "Limeade",         "slug": "limeade"},
    {"name": "Glint",           "slug": "glintinc"},
    {"name": "Leapsome",        "slug": "leapsome"},
    {"name": "15Five",          "slug": "15five"},
    {"name": "Betterworks",     "slug": "betterworks"},
    {"name": "Reflektive",      "slug": "reflektive"},
    # ── Healthcare ──
    {"name": "Accolade",        "slug": "accolade"},
    {"name": "Included Health", "slug": "included-health"},
    {"name": "Sword Health",    "slug": "swordhealth"},
    {"name": "Transcarent",     "slug": "transcarent"},
    {"name": "Cityblock",       "slug": "cityblock"},
    {"name": "Ro",              "slug": "ro"},
    # ── Climate Tech ──
    {"name": "Arcadia",         "slug": "arcadia"},
    {"name": "Palmetto",        "slug": "palmetto"},
    {"name": "Swell Energy",    "slug": "swell"},
    {"name": "Electreon",       "slug": "electreon"},
    # ── Consumer ──
    {"name": "Duolingo",        "slug": "duolingo"},
    {"name": "Calm",            "slug": "calm"},
    {"name": "Headspace",       "slug": "headspace"},
    {"name": "BetterUp",        "slug": "betterup"},
    {"name": "MasterClass",     "slug": "masterclass"},
    {"name": "Coursera",        "slug": "coursera"},
    {"name": "Udemy",           "slug": "udemy"},
    {"name": "Brilliant",       "slug": "brilliant"},
    {"name": "Quizlet",         "slug": "quizlet"},
    {"name": "Chegg",           "slug": "chegg"},
    # ── Crypto / Web3 ──
    {"name": "Alchemy",         "slug": "alchemy-insights"},
    {"name": "Chainalysis",     "slug": "chainalysis"},
    {"name": "Anchorage",       "slug": "anchorage"},
    {"name": "Fireblocks",      "slug": "fireblocks"},
    {"name": "Paxos",           "slug": "paxos"},
    {"name": "Gemini",          "slug": "gemini"},
    {"name": "Kraken",          "slug": "kraken"},
    {"name": "Bitso",           "slug": "bitso"},
    # ── International ──
    {"name": "Revolut",         "slug": "revolut"},
    {"name": "Wise",            "slug": "wise"},
    {"name": "Monzo",           "slug": "monzo"},
    {"name": "Starling Bank",   "slug": "starlingbank"},
    {"name": "N26",             "slug": "n26"},
    {"name": "Nubank",          "slug": "nubank"},
    {"name": "Rappi",           "slug": "rappi"},
    {"name": "Mercado Libre",   "slug": "mercadolibre"},
    {"name": "Grab",            "slug": "grab"},
    {"name": "Gojek",           "slug": "gojek"},
    {"name": "Bukalapak",       "slug": "bukalapak"},
    {"name": "Tokopedia",       "slug": "tokopedia"},
    {"name": "Razorpay",        "slug": "razorpay"},
    {"name": "CRED",            "slug": "dreamplug-technologies"},
    {"name": "Zepto",           "slug": "zepto"},
    {"name": "Meesho",          "slug": "meesho"},
    {"name": "PhonePe",         "slug": "phonepe"},
    {"name": "Ola",             "slug": "animithinc"},
    {"name": "Swiggy",          "slug": "swiggy"},
    {"name": "Zomato",          "slug": "zomato"},
    {"name": "Paytm",           "slug": "paytm"},
    {"name": "BrowserStack",    "slug": "browserstack"},
    {"name": "Postman",         "slug": "postman"},
    {"name": "Hasura",          "slug": "hasura"},
    {"name": "Chargebee",       "slug": "chargebee"},
    {"name": "Freshworks",      "slug": "freshworks"},
    {"name": "Zoho",            "slug": "zoho"},
    {"name": "CleverTap",       "slug": "clevertap"},
    {"name": "MoEngage",        "slug": "moengage"},
    {"name": "WebEngage",       "slug": "webengage"},
    {"name": "Healthifyme",     "slug": "healthifyme"},
    {"name": "Cure.fit",        "slug": "cult-fit"},
]
