services:
  - type: web
    name: cv-ats-job-finder
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app -c gunicorn.conf.py
    plan: starter
    region: singapore
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
